/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "I2C/I2C.h"

I2C_Config CS43L22_Driver;

int8_t CS43L22_Init(void);

int main(void)
{
	MCU_Clock_Setup();
	Delay_Config();
	CS43L22_Driver.Port = I2C1;
	CS43L22_Driver.SCL_Pin = I2C_Configuration.Pin.__I2C1__.SCL.PB6;
	CS43L22_Driver.SDA_Pin = I2C_Configuration.Pin.__I2C1__.SDA.PB9;
	CS43L22_Driver.DMA_Control = I2C_Configuration.DMA_Control.Disable;
	CS43L22_Driver.Interrupts = I2C_Configuration.Interrupts.Disable;
	CS43L22_Driver.Mode = I2C_Configuration.Mode.Master;
	CS43L22_Driver.Speed_Mode = I2C_Configuration.Speed_Mode.FM_Mode;
	I2C_Init(&CS43L22_Driver);






	for(;;);
}


int8_t CS43L22_Init(void)
{
	CS43L22_Driver.Port = I2C1;
	CS43L22_Driver.SCL_Pin = I2C_Configuration.Pin.__I2C1__.SCL.PB6;
	CS43L22_Driver.SDA_Pin = I2C_Configuration.Pin.__I2C1__.SDA.PB9;
	CS43L22_Driver.DMA_Control = I2C_Configuration.DMA_Control.Disable;
	CS43L22_Driver.Interrupts = I2C_Configuration.Interrupts.Disable;
	CS43L22_Driver.Mode = I2C_Configuration.Mode.Master;
	CS43L22_Driver.Speed_Mode = I2C_Configuration.Speed_Mode.FM_Mode;
	I2C_Init(&CS43L22_Driver);

	GPIO_Pin_Init(GPIOD, 4, GPIO_Configuration.Mode.General_Purpose_Output, GPIO_Configuration.Output_Type.Push_Pull, GPIO_Configuration.Speed.Very_High_Speed, GPIO_Configuration.Pull.Pull_Up, GPIO_Configuration.Alternate_Functions.None);

	GPIO_Pin_High(GPIOD, 4);

	I2C_Master_Write_Register(&CS43L22_Driver, 0x4A, 0x02, 0b00000001);

	return 1;
}

int8_t CS43L22_Read_ID(void)
{
	int8_t retval = 0;
	uint8_t temp = 0;
	temp = I2C_Master_Read_Register(&CS43L22_Driver, 0x4A, 0x01);

	if((temp & 0xF0) == 0xE0)
	{
		retval = 1;
	}
	else
	{
		retval = 0;
	}

	return retval;
}



